[versions]
junit-jupiter = "5.10.1"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.4.14" }
gwt-exporter = { module = "org.timepedia.exporter:gwtexporter", version = "2.5.1" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
apache-commons-math3 = { module = "org.apache.commons:commons-math3", version = "3.6.1" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
dependency-versions = { id = "com.github.ben-manes.versions", version = "0.50.0" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
