[versions]
junit-jupiter = "5.5.2"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.2.10" }
gwt-exporter = { module = "org.timepedia.exporter:gwtexporter", version = "2.5.1" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }
dependency-versions = { id = "com.github.ben-manes.versions", version = "0.42.0" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }
